owner: PrismPipeline # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository


sites:
  - name: Prism-Pipeline Website
    url: https://prism-pipeline.com/impressum/
  - name: Prism-Pipeline License Server
    url: https://service.prism-pipeline.com
    icon: https://prism-pipeline.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /upptime
  cname: status.prism-pipeline.com
  name: Prism Pipeline - Upptime
  logoUrl: https://status.prism-pipeline.com/prism-logo-icon.png
  introTitle: Prism Pipeline Status
  # theme: night
  themeUrl: https://status.prism-pipeline.com/prism-theme.css
  favicon: https://status.prism-pipeline.com/favicon.png
  navbar:
    - title: Status
      href: /
    - title: Go to Prism Pipeline
      href: https://prism-pipeline.com
  
      
i18n:
  # Change default footer
  footer: If you have any questions, please contact us at contact@prism-pipeline.com.




# Optional: Email configuration
#email:
#  smtp_server: "smtp.yourmail.com"
#  smtp_port: 587
#  smtp_user: "your-email@example.com"
#  smtp_password: "your-email-password"
#  from_address: "your-email@example.com"
#  to_address: "your-email@example.com"
  
# Optional: Custom status labels for the different states
#status_labels:
#  operational: "All Systems Operational"
# degraded: "Degraded Performance"
# maintenance: "Under Maintenance"

  
  
